name: CI for Python Web App

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    environment: test

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (needed for advanced Docker builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build the Docker image
      - name: Build Docker image
        run: docker build -t telegram-gpt .

      # Step 4: Run tests in Docker container and set environment variables
      - name: Run tests
        env:
          TEST_ENV_VAR: ${{ secrets.TEST_ENV_VAR }}
        run: docker run --entrypoint pytest telegram-gpt tests/